name: Branch Build & Package

run-name: >-
  📦 Build & Package
  ${{ 
    format('from {0}: {1} by @{2}', github.ref_name, github.event.head_commit.message, github.actor)
  }}

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '**/*.md'
      - 'assets/**'

jobs:
  package:
    uses: ./.github/workflows/reuse-package.yml
