name: MacOS Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run ktlintFormat
        run: ./gradlew ktlintFormat

      - name: Build shadowJar
        run: ./gradlew shadowJar

      - name: Package .dmg with jpackage (macOS)
        shell: bash
        run: |
          APP_VERSION="1.0.${{ github.run_number }}"
          JAR_FILE=$(basename $(find build/libs -name "super-share-*.jar"))
          jpackage \
          --type dmg \
          --name SuperShare \
          --input build/libs \
          --main-jar "$JAR_FILE" \
          --main-class MainKt \
          --app-version "$APP_VERSION" \
          --icon assets/file-transformer.icns \
          --vendor "zeyan-du"

      - name: Upload .dmg artifact (macOS)
        uses: actions/upload-artifact@v4
        with:
          name: super-share-dmg
          path: SuperShare-*.dmg
