name: Windows Build and Package

on:
  workflow_call:
  push:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '**/*.md'
      - 'assets/**'

jobs:
  build-jar:
    uses: ./.github/workflows/build-jar.yml
    with:
      runs-on: windows-latest
      java-version: '21'
      distribution: 'temurin'
      artifact-suffix: 'windows'

  package:
    runs-on: windows-latest
    needs: build-jar
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: super-share-jar-windows
          path: build/libs

      - name: Package portable app with jpackage (Windows)
        shell: bash
        run: |
          APP_VERSION="1.0.${{ github.run_number }}"
          JAR_FILE=$(basename $(find build/libs -name "super-share-*.jar"))
          jpackage \
          --type app-image \
          --name SuperShare \
          --input build/libs \
          --main-jar "$JAR_FILE" \
          --main-class MainKt \
          --app-version "$APP_VERSION" \
          --vendor "zeyan" \
          --icon src/main/resources/icons/file-share.ico \
          --dest build/dist

      - name: Zip the portable app
        shell: pwsh
        run: |
          Compress-Archive -Path build/dist/SuperShare/* -DestinationPath build/dist/SuperShare-windows-portable.zip

      - name: Upload portable app artifact (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: super-share-windows-portable-${{ github.run_number }}
          path: build/dist/SuperShare-windows-portable.zip
