name: MacOS Build and Package

env:
  RUNNER: macos-latest

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '**/*.md'
      - 'assets/**'

jobs:
  build:
    runs-on: ${{ env.RUNNER }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - uses: ./.github/workflows/build-jar.yml
        with:
          runs-on: macos-latest
          java-version: '21'
          distribution: 'temurin'

      - name: Package .dmg with jpackage (macOS)
        shell: bash
        run: |
          APP_VERSION="1.0.${{ github.run_number }}"
          JAR_FILE=$(basename $(find build/libs -name "super-share-*.jar"))
          jpackage \
          --type dmg \
          --name SuperShare \
          --input build/libs \
          --main-jar "$JAR_FILE" \
          --main-class MainKt \
          --app-version "$APP_VERSION" \
          --icon src/main/resources/icons/file-transformer.icns \
          --vendor "zeyan-du"

      - name: Upload .dmg artifact (macOS)
        uses: actions/upload-artifact@v4
        with:
          name: super-share-dmg
          path: SuperShare-*.dmg
