name: Windows Build and Package

env:
  RUNNER: windows-latest
  JAVA_VERSION: '21'
  JAVA_DISTRIBUTION: 'temurin'

on:
  push:
    branches-ignore: [ main ]

jobs:
  build:
    runs-on: ${{ env.RUNNER }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - uses: ./.github/workflows/build-jar.yml
        with:
          runs-on: ${{ env.RUNNER }}
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Package portable app with jpackage (Windows)
        shell: bash
        run: |
          APP_VERSION="1.0.${{ github.run_number }}"
          JAR_FILE=$(basename $(find build/libs -name "super-share-*.jar"))
          jpackage \
          --type app-image \
          --name SuperShare \
          --input build/libs \
          --main-jar "$JAR_FILE" \
          --main-class MainKt \
          --app-version "$APP_VERSION" \
          --vendor "zeyan" \
          --icon src/main/resources/icons/file-share.ico \
          --dest build/dist

      - name: Zip the portable app
        shell: pwsh
        run: |
          Compress-Archive -Path build/dist/SuperShare/* -DestinationPath build/dist/SuperShare-windows-portable.zip

      - name: Upload portable app artifact (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: super-share-windows-portable-${{ github.run_number }}
          path: build/dist/SuperShare-windows-portable.zip
