name: Build, Package and Release

permissions:
  contents: write

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build-and-package-macos:
    runs-on: macos-latest
    steps:
      - uses: ./.github/workflows/build-jar.yml

      - name: Package .dmg with jpackage (macOS)
        shell: bash
        run: |
          APP_VERSION="1.0.${{ github.run_number }}"
          JAR_FILE=$(basename $(find build/libs -name "super-share-*.jar"))
          jpackage \
          --type dmg \
          --name SuperShare \
          --input build/libs \
          --main-jar "$JAR_FILE" \
          --main-class MainKt \
          --app-version "$APP_VERSION" \
          --icon src/main/resources/icons/file-transformer.icns \
          --vendor "zeyan-du"

      - name: Upload .dmg artifact
        uses: actions/upload-artifact@v4
        with:
          name: super-share-dmg
          path: SuperShare-*.dmg
      
      - name: Upload .jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: super-share-jar
          path: build/libs/super-share-*.jar


  build-and-package-windows:
    runs-on: windows-latest
    steps:
      - uses: ./.github/workflows/build-jar.yml

      - name: Package portable app with jpackage (Windows)
        shell: bash
        run: |
          APP_VERSION="1.0.${{ github.run_number }}"
          JAR_FILE=$(basename $(find build/libs -name "super-share-*.jar"))
          jpackage \
          --type app-image \
          --name SuperShare \
          --input build/libs \
          --main-jar "$JAR_FILE" \
          --main-class MainKt \
          --app-version "$APP_VERSION" \
          --vendor "zeyan" \
          --icon src/main/resources/icons/file-share.ico \
          --dest build/dist

      - name: Zip the portable app
        shell: pwsh
        run: |
          Compress-Archive -Path build/dist/SuperShare/* -DestinationPath build/dist/SuperShare-windows-portable.zip

      - name: Upload portable app artifact
        uses: actions/upload-artifact@v4
        with:
          name: super-share-windows-portable
          path: build/dist/SuperShare-windows-portable.zip

  release:
    needs: [ build-and-package-macos, build-and-package-windows ]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release and Upload Artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/super-share-dmg/*
            artifacts/super-share-windows-portable/*
            artifacts/super-share-jar/*
          tag_name: "v1.0.${{ github.run_number }}"
          body: "Automated release based on commit ${{ github.sha }}"
          draft: false
          prerelease: false
