name: Release

permissions:
  contents: write

on:
  push:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '**/*.md'
      - 'assets/**'

jobs:
  package-macos:
    uses: ./.github/workflows/build-macos.yml

  package-windows:
    runs-on: windows-latest
    needs: package-macos
    steps:
    - name: Download JAR artifact
      uses: actions/download-artifact@v4
      with:
        name: super-share-jar
        path: build/libs

    - name: Package portable app with jpackage
      shell: bash
      run: |
        APP_VERSION="1.0.${{ github.run_number }}"
        JAR_FILE=$(basename $(find build/libs -name "super-share-*.jar"))
        jpackage \
        --type app-image \
        --name SuperShare \
        --input build/libs \
        --main-jar "$JAR_FILE" \
        --main-class MainKt \
        --app-version "$APP_VERSION" \
        --vendor "zeyan" \
        --icon src/main/resources/icons/file-share.ico \
        --dest build/dist

    - name: Zip the portable app
      shell: pwsh
      run: |
        Compress-Archive -Path build/dist/SuperShare/* -DestinationPath build/dist/SuperShare-windows-portable.zip

    - name: Upload portable app artifact (Windows)
      uses: actions/upload-artifact@v4
      with:
        name: super-share-windows-portable-${{ github.run_number }}
        path: build/dist/SuperShare-windows-portable.zip

  release:
    needs: [ package-macos, package-windows ]
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && 
       github.event.pull_request.merged == true && 
       startsWith(github.head_ref, 'releases/'))
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release and Upload Artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/super-share-dmg/*
            artifacts/super-share-windows-portable/*
            artifacts/super-share-jar-macos/*
            artifacts/super-share-jar-windows/*
          tag_name: "v1.0.${{ github.run_number }}"
          body: "Automated release based on commit ${{ github.sha }}"
          draft: false
          prerelease: false
