name: Release

permissions:
  contents: write

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '**/*.md'
      - 'assets/**'

jobs:
  package-windows:
    uses: ./.github/workflows/build-windows.yml

  package-macos:
    uses: ./.github/workflows/build-macos.yml

  release:
    needs: [ package-macos, package-windows ]
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && 
       github.event.pull_request.merged == true && 
       startsWith(github.head_ref, 'releases/'))
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release and Upload Artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/super-share-dmg/*
            artifacts/super-share-windows-portable/*
            artifacts/super-share-jar-macos/*
            artifacts/super-share-jar-windows/*
          tag_name: "v1.0.${{ github.run_number }}"
          body: "Automated release based on commit ${{ github.sha }}"
          draft: false
          prerelease: false
