name: Download JAR and Package (Cross-Platform)

on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
      jar-artifact-name:
        required: true
        type: string

jobs:
  package:
    name: Package for ${{ inputs.runs-on == 'windows-latest' && 'Windows' || inputs.runs-on == 'macos-latest' && 'macOS' || inputs.runs-on == 'ubuntu-latest' && 'Linux' || inputs.runs-on }}
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.jar-artifact-name }}
          path: build/libs

      - name: Package portable app with jpackage (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          APP_VERSION="1.0.${{ github.run_number }}"
          JAR_FILE=$(basename $(find build/libs -name "super-share-*.jar"))
          jpackage \
          --type app-image \
          --name SuperShare \
          --input build/libs \
          --main-jar "$JAR_FILE" \
          --main-class MainKt \
          --app-version "$APP_VERSION" \
          --vendor "zeyan" \
          --icon src/main/resources/icons/file-share.ico \
          --dest build/dist

      - name: Zip the portable app (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Compress-Archive -Path build/dist/SuperShare/* -DestinationPath build/dist/SuperShare-portable.zip

      - name: Package .dmg with jpackage (macOS)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          APP_VERSION="1.0.${{ github.run_number }}"
          JAR_FILE=$(basename $(find build/libs -name "super-share-*.jar"))
          jpackage \
          --type dmg \
          --name SuperShare \
          --input build/libs \
          --main-jar "$JAR_FILE" \
          --main-class MainKt \
          --app-version "$APP_VERSION" \
          --icon src/main/resources/icons/file-transformer.icns \
          --vendor "zeyan-du"

      - name: Upload packaged artifact
        uses: actions/upload-artifact@v4
        with:
          name: super-share-${{ runner.os == 'Windows' && 'windows' || 'macos' }}-${{ github.run_number }}
          path: |
            build/dist/SuperShare-portable.zip
            SuperShare-*.dmg
